export const GET_SERVICE_STATUS = 'GET_SERVICE_STATUS';

export const REQUEST_TRANSPORT_SERVICES = 'REQUEST_TRANSPORT_SERVICES';

export const RESPONSE_TRANSPORT_SERVICES = 'RESPONSE_TRANSPORT_SERVICES';

export const REQUEST_SEARCH_CYCLE = 'REQUEST_SEARCH_CYCLE';

export const RESPONSE_SEARCH_CYCLE = 'RESPONSE_SEARCH_CYCLE';

